"""W2 service plan notice table, guards, and grants.

Revision ID: 20260809_0018_w2_service_plan_notice
Revises: 20260808_0017_recipient_guardian_email
Create Date: 2026-08-09
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260809_0018_w2_service_plan_notice"
down_revision: str | None = "20260808_0017_recipient_guardian_email"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE erp.recipient_service_plan_notice (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            recipient_contract_id BIGINT NOT NULL,
            notification_date DATE NOT NULL,
            applied_start_date DATE NOT NULL,
            applied_end_date DATE NOT NULL,
            invalidated_at_utc TIMESTAMP WITH TIME ZONE,
            replacement_service_plan_notice_id BIGINT,
            created_by_account_id BIGINT NOT NULL,
            created_at_utc TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_by_account_id BIGINT NOT NULL,
            updated_at_utc TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            row_version INTEGER DEFAULT 1 NOT NULL,
            CONSTRAINT pk_recipient_service_plan_notice PRIMARY KEY (id),
            CONSTRAINT fk_service_plan_notice_recipient_contract
                FOREIGN KEY (recipient_contract_id)
                REFERENCES erp.recipient_contract (id) ON DELETE RESTRICT,
            CONSTRAINT fk_service_plan_notice_replacement
                FOREIGN KEY (replacement_service_plan_notice_id)
                REFERENCES erp.recipient_service_plan_notice (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_service_plan_notice_created_by_account
                FOREIGN KEY (created_by_account_id)
                REFERENCES erp.user_account (id) ON DELETE RESTRICT,
            CONSTRAINT fk_service_plan_notice_updated_by_account
                FOREIGN KEY (updated_by_account_id)
                REFERENCES erp.user_account (id) ON DELETE RESTRICT,
            CONSTRAINT ck_service_plan_notice_date_order
                CHECK (applied_end_date >= applied_start_date),
            CONSTRAINT ck_service_plan_notice_row_version_positive
                CHECK (row_version > 0)
        )
        """
    )

    op.execute(
        """
        CREATE FUNCTION erp.fn_service_plan_notice_before_contract_start()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.invalidated_at_utc IS NULL
               AND EXISTS (
                   SELECT 1
                   FROM erp.recipient_contract contract
                   WHERE contract.id = NEW.recipient_contract_id
                     AND NEW.applied_start_date < contract.start_date
               ) THEN
                RAISE EXCEPTION 'service_plan_before_contract_start'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_service_plan_notice_within_contract()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.invalidated_at_utc IS NULL THEN
                IF EXISTS (
                    SELECT 1
                    FROM erp.recipient_contract contract
                    WHERE contract.id = NEW.recipient_contract_id
                      AND contract.invalidated_at_utc IS NOT NULL
                ) THEN
                    RAISE EXCEPTION 'service_plan_contract_invalidated'
                        USING ERRCODE = '23514';
                END IF;
                IF EXISTS (
                    SELECT 1
                    FROM erp.recipient_contract contract
                    WHERE contract.id = NEW.recipient_contract_id
                      AND contract.end_date IS NOT NULL
                      AND NEW.applied_end_date > contract.end_date
                ) THEN
                    RAISE EXCEPTION 'service_plan_outside_contract_period'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_service_plan_notice_within_certification()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.invalidated_at_utc IS NULL
               AND NOT EXISTS (
                   SELECT 1
                   FROM erp.recipient_contract contract
                   WHERE contract.id = NEW.recipient_contract_id
                     AND daterange(
                             NEW.applied_start_date,
                             NEW.applied_end_date + 1,
                             '[)'
                         )
                         <@ COALESCE(
                             (
                                 SELECT range_agg(cert.certification_period)
                                 FROM erp.recipient_certification_period cert
                                 WHERE cert.recipient_id = contract.recipient_id
                                   AND cert.invalidated_at_utc IS NULL
                             ),
                             '{}'::datemultirange
                         )
               ) THEN
                RAISE EXCEPTION 'service_plan_outside_certification_period'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_recipient_contract_service_plan_reverse_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF OLD.recipient_id IS DISTINCT FROM NEW.recipient_id
               AND EXISTS (
                   SELECT 1
                   FROM erp.recipient_service_plan_notice plan
                   WHERE plan.recipient_contract_id IN (OLD.id, NEW.id)
                     AND plan.invalidated_at_utc IS NULL
               ) THEN
                RAISE EXCEPTION
                    'service_plan_contract_orphan recipient_id change forbidden'
                    USING ERRCODE = '23514';
            END IF;
            IF EXISTS (
                SELECT 1
                FROM erp.recipient_service_plan_notice plan
                WHERE plan.recipient_contract_id = NEW.id
                  AND plan.invalidated_at_utc IS NULL
                  AND NEW.invalidated_at_utc IS NOT NULL
            ) THEN
                RAISE EXCEPTION 'service_plan_contract_invalidated'
                    USING ERRCODE = '23514';
            END IF;
            IF EXISTS (
                SELECT 1
                FROM erp.recipient_service_plan_notice plan
                WHERE plan.recipient_contract_id = NEW.id
                  AND plan.invalidated_at_utc IS NULL
                  AND plan.applied_start_date < NEW.start_date
            ) THEN
                RAISE EXCEPTION 'service_plan_before_contract_start'
                    USING ERRCODE = '23514';
            END IF;
            IF EXISTS (
                SELECT 1
                FROM erp.recipient_service_plan_notice plan
                WHERE plan.recipient_contract_id = NEW.id
                  AND plan.invalidated_at_utc IS NULL
                  AND NEW.end_date IS NOT NULL
                  AND plan.applied_end_date > NEW.end_date
            ) THEN
                RAISE EXCEPTION 'service_plan_outside_contract_period'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_recipient_contract_recipient_id_immutable()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF OLD.recipient_id IS DISTINCT FROM NEW.recipient_id THEN
                RAISE EXCEPTION
                    'recipient_contract.recipient_id is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_recipient_certification_period_service_plan_reverse_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            rid bigint;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                rid := OLD.recipient_id;
                IF EXISTS (
                    SELECT 1
                    FROM erp.recipient_service_plan_notice plan
                    JOIN erp.recipient_contract contract
                      ON contract.id = plan.recipient_contract_id
                    WHERE contract.recipient_id = rid
                      AND plan.invalidated_at_utc IS NULL
                      AND NOT (
                          daterange(
                              plan.applied_start_date,
                              plan.applied_end_date + 1,
                              '[)'
                          )
                          <@ COALESCE(
                              (
                                  SELECT range_agg(cert.certification_period)
                                  FROM erp.recipient_certification_period cert
                                  WHERE cert.recipient_id = rid
                                    AND cert.invalidated_at_utc IS NULL
                              ),
                              '{}'::datemultirange
                          )
                      )
                ) THEN
                    RAISE EXCEPTION 'service_plan_outside_certification_period'
                        USING ERRCODE = '23514';
                END IF;
                RETURN OLD;
            END IF;

            rid := NEW.recipient_id;
            IF EXISTS (
                SELECT 1
                FROM erp.recipient_service_plan_notice plan
                JOIN erp.recipient_contract contract
                  ON contract.id = plan.recipient_contract_id
                WHERE contract.recipient_id = rid
                  AND plan.invalidated_at_utc IS NULL
                  AND NOT (
                      daterange(
                          plan.applied_start_date,
                          plan.applied_end_date + 1,
                          '[)'
                      )
                      <@ COALESCE(
                          (
                              SELECT range_agg(cert.certification_period)
                              FROM erp.recipient_certification_period cert
                              WHERE cert.recipient_id = rid
                                AND cert.invalidated_at_utc IS NULL
                          ),
                          '{}'::datemultirange
                      )
                  )
            ) THEN
                RAISE EXCEPTION 'service_plan_outside_certification_period'
                    USING ERRCODE = '23514';
            END IF;

            IF TG_OP = 'UPDATE'
               AND OLD.recipient_id IS DISTINCT FROM NEW.recipient_id THEN
                rid := OLD.recipient_id;
                IF EXISTS (
                    SELECT 1
                    FROM erp.recipient_service_plan_notice plan
                    JOIN erp.recipient_contract contract
                      ON contract.id = plan.recipient_contract_id
                    WHERE contract.recipient_id = rid
                      AND plan.invalidated_at_utc IS NULL
                      AND NOT (
                          daterange(
                              plan.applied_start_date,
                              plan.applied_end_date + 1,
                              '[)'
                          )
                          <@ COALESCE(
                              (
                                  SELECT range_agg(cert.certification_period)
                                  FROM erp.recipient_certification_period cert
                                  WHERE cert.recipient_id = rid
                                    AND cert.invalidated_at_utc IS NULL
                              ),
                              '{}'::datemultirange
                          )
                      )
                ) THEN
                    RAISE EXCEPTION 'service_plan_outside_certification_period'
                        USING ERRCODE = '23514';
                END IF;
            END IF;

            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_recipient_certification_period_recipient_id_immutable()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF OLD.recipient_id IS DISTINCT FROM NEW.recipient_id THEN
                RAISE EXCEPTION
                    'recipient_certification_period.recipient_id is immutable'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END
        $$
        """
    )

    op.execute(
        """
        CREATE CONSTRAINT TRIGGER ct_service_plan_notice_before_contract_start
        AFTER INSERT OR UPDATE ON erp.recipient_service_plan_notice
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION erp.fn_service_plan_notice_before_contract_start();

        CREATE CONSTRAINT TRIGGER ct_service_plan_notice_within_contract
        AFTER INSERT OR UPDATE ON erp.recipient_service_plan_notice
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION erp.fn_service_plan_notice_within_contract();

        CREATE CONSTRAINT TRIGGER ct_service_plan_notice_within_certification
        AFTER INSERT OR UPDATE ON erp.recipient_service_plan_notice
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION erp.fn_service_plan_notice_within_certification();

        CREATE CONSTRAINT TRIGGER ct_recipient_contract_service_plan_reverse_guard
        AFTER UPDATE ON erp.recipient_contract
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION erp.fn_recipient_contract_service_plan_reverse_guard();

        CREATE CONSTRAINT TRIGGER
            ct_recipient_certification_period_service_plan_reverse_guard
        AFTER INSERT OR UPDATE OR DELETE ON erp.recipient_certification_period
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION
            erp.fn_recipient_certification_period_service_plan_reverse_guard();

        CREATE TRIGGER ct_recipient_contract_recipient_id_immutable
        BEFORE UPDATE ON erp.recipient_contract
        FOR EACH ROW
        EXECUTE FUNCTION erp.fn_recipient_contract_recipient_id_immutable();

        CREATE TRIGGER ct_recipient_certification_period_recipient_id_immutable
        BEFORE UPDATE ON erp.recipient_certification_period
        FOR EACH ROW
        EXECUTE FUNCTION erp.fn_recipient_certification_period_recipient_id_immutable()
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='erp_app') THEN
          GRANT USAGE ON SCHEMA erp TO erp_app;
          GRANT SELECT, INSERT, UPDATE ON TABLE erp.recipient_service_plan_notice TO erp_app;
          REVOKE DELETE, TRUNCATE ON TABLE erp.recipient_service_plan_notice FROM erp_app;
          GRANT USAGE, SELECT ON SEQUENCE erp.recipient_service_plan_notice_id_seq TO erp_app;
        END IF;
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='erp_backup') THEN
          GRANT USAGE ON SCHEMA erp TO erp_backup;
          GRANT SELECT ON TABLE erp.recipient_service_plan_notice TO erp_backup;
          REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE erp.recipient_service_plan_notice FROM erp_backup;
          GRANT SELECT ON SEQUENCE erp.recipient_service_plan_notice_id_seq TO erp_backup;
          REVOKE USAGE ON SEQUENCE erp.recipient_service_plan_notice_id_seq FROM erp_backup;
        END IF;
        END $$
        """
    )


def downgrade() -> None:
    # (1) Forward-guard triggers + functions on recipient_service_plan_notice
    op.execute(
        """
        DROP TRIGGER IF EXISTS ct_service_plan_notice_before_contract_start
            ON erp.recipient_service_plan_notice;
        DROP TRIGGER IF EXISTS ct_service_plan_notice_within_contract
            ON erp.recipient_service_plan_notice;
        DROP TRIGGER IF EXISTS ct_service_plan_notice_within_certification
            ON erp.recipient_service_plan_notice;
        DROP FUNCTION IF EXISTS erp.fn_service_plan_notice_before_contract_start();
        DROP FUNCTION IF EXISTS erp.fn_service_plan_notice_within_contract();
        DROP FUNCTION IF EXISTS erp.fn_service_plan_notice_within_certification();
        """
    )

    # (2) Reverse-guard triggers + functions on parent tables
    op.execute(
        """
        DROP TRIGGER IF EXISTS ct_recipient_contract_service_plan_reverse_guard
            ON erp.recipient_contract;
        DROP TRIGGER IF EXISTS
            ct_recipient_certification_period_service_plan_reverse_guard
            ON erp.recipient_certification_period;
        DROP FUNCTION IF EXISTS erp.fn_recipient_contract_service_plan_reverse_guard();
        DROP FUNCTION IF EXISTS
            erp.fn_recipient_certification_period_service_plan_reverse_guard();
        """
    )

    # (3) recipient_id immutability triggers + functions
    op.execute(
        """
        DROP TRIGGER IF EXISTS ct_recipient_contract_recipient_id_immutable
            ON erp.recipient_contract;
        DROP TRIGGER IF EXISTS ct_recipient_certification_period_recipient_id_immutable
            ON erp.recipient_certification_period;
        DROP FUNCTION IF EXISTS erp.fn_recipient_contract_recipient_id_immutable();
        DROP FUNCTION IF EXISTS
            erp.fn_recipient_certification_period_recipient_id_immutable();
        """
    )

    # (4) Grant revoke
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_app') THEN
                REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE
                    erp.recipient_service_plan_notice FROM erp_app;
                IF to_regclass('erp.recipient_service_plan_notice_id_seq') IS NOT NULL THEN
                    REVOKE USAGE, SELECT ON SEQUENCE
                        erp.recipient_service_plan_notice_id_seq FROM erp_app;
                END IF;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_backup') THEN
                REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE
                    erp.recipient_service_plan_notice FROM erp_backup;
                IF to_regclass('erp.recipient_service_plan_notice_id_seq') IS NOT NULL THEN
                    REVOKE USAGE, SELECT ON SEQUENCE
                        erp.recipient_service_plan_notice_id_seq FROM erp_backup;
                END IF;
            END IF;
        END
        $$;
        """
    )

    # (5) Drop table (identity sequence drops with it)
    op.execute("DROP TABLE IF EXISTS erp.recipient_service_plan_notice;")
