"""Add W1E GENERAL care assignment ledger and guards.

Revision ID: 20260801_0012_w1e_care_assignment
Revises: 20260730_0011_w1d_recipient_contract
Create Date: 2026-08-01
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260801_0012_w1e_care_assignment"
down_revision: str | None = "20260730_0011_w1d_recipient_contract"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TABLE = "care_assignment"


def _actor_columns() -> tuple[sa.Column[object], ...]:
    return (
        sa.Column("created_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("updated_by_account_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at_utc",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("row_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )


def _actor_constraints(table_name: str) -> tuple[sa.ForeignKeyConstraint, ...]:
    return (
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["erp.user_account.id"],
            name=f"fk_{table_name}_created_by_account",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_account_id"],
            ["erp.user_account.id"],
            name=f"fk_{table_name}_updated_by_account",
            ondelete="RESTRICT",
        ),
    )


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE erp.care_assignment (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            recipient_contract_id BIGINT NOT NULL,
            staff_id BIGINT NOT NULL,
            employment_id BIGINT NOT NULL,
            assignment_kind TEXT NOT NULL,
            family_relationship_text TEXT,
            start_date DATE NOT NULL,
            end_date DATE,
            assignment_period DATERANGE GENERATED ALWAYS AS
                (daterange(start_date, end_date + 1, '[)')) STORED NOT NULL,
            invalidated_at_utc TIMESTAMP WITH TIME ZONE,
            replacement_assignment_id BIGINT,
            created_by_account_id BIGINT NOT NULL,
            created_at_utc TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            updated_by_account_id BIGINT NOT NULL,
            updated_at_utc TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            row_version INTEGER DEFAULT 1 NOT NULL,
            CONSTRAINT pk_care_assignment PRIMARY KEY (id),
            CONSTRAINT fk_care_assignment_recipient_contract
                FOREIGN KEY (recipient_contract_id)
                REFERENCES erp.recipient_contract (id) ON DELETE RESTRICT,
            CONSTRAINT fk_care_assignment_employment
                FOREIGN KEY (staff_id, employment_id)
                REFERENCES erp.staff_employment (staff_id, id) ON DELETE RESTRICT,
            CONSTRAINT fk_care_assignment_replacement
                FOREIGN KEY (replacement_assignment_id)
                REFERENCES erp.care_assignment (id)
                ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT fk_care_assignment_created_by_account
                FOREIGN KEY (created_by_account_id)
                REFERENCES erp.user_account (id) ON DELETE RESTRICT,
            CONSTRAINT fk_care_assignment_updated_by_account
                FOREIGN KEY (updated_by_account_id)
                REFERENCES erp.user_account (id) ON DELETE RESTRICT,
            CONSTRAINT ck_care_assignment_kind
                CHECK (assignment_kind IN ('GENERAL','FAMILY')),
            CONSTRAINT ck_care_assignment_date_order
                CHECK (end_date IS NULL OR start_date <= end_date),
            CONSTRAINT ck_care_assignment_row_version_positive
                CHECK (row_version > 0),
            CONSTRAINT ex_care_assignment_same_contract_staff_period
                EXCLUDE USING gist (
                    recipient_contract_id WITH =,
                    staff_id WITH =,
                    assignment_period WITH &&
                ) WHERE (invalidated_at_utc IS NULL)
        );
        """
    )

    op.execute(
        """
        CREATE FUNCTION erp.fn_care_assignment_within_contract()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.invalidated_at_utc IS NULL AND NOT EXISTS (
                SELECT 1
                FROM erp.recipient_contract contract
                WHERE contract.id = NEW.recipient_contract_id
                  AND contract.invalidated_at_utc IS NULL
                  AND NEW.assignment_period <@ contract.contract_period
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'CARE_ASSIGNMENT_OUTSIDE_CONTRACT_PERIOD';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_care_assignment_within_employment()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.invalidated_at_utc IS NULL AND NOT EXISTS (
                SELECT 1
                FROM erp.staff_employment employment
                WHERE employment.id = NEW.employment_id
                  AND employment.staff_id = NEW.staff_id
                  AND employment.invalidated_at_utc IS NULL
                  AND NEW.assignment_period <@ employment.employment_period
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'CARE_ASSIGNMENT_OUTSIDE_EMPLOYMENT_PERIOD';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_care_assignment_within_position()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.invalidated_at_utc IS NULL
               AND NEW.assignment_kind = 'GENERAL'
               AND NOT (
                   NEW.assignment_period <@ COALESCE(
                       (
                           SELECT range_agg(position.position_period)
                           FROM erp.staff_position_period position
                           WHERE position.staff_id = NEW.staff_id
                             AND position.employment_id = NEW.employment_id
                             AND position.position_code = 'CARE_WORKER'
                             AND position.invalidated_at_utc IS NULL
                       ), '{}'::datemultirange
                   )
               )
            THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'CARE_ASSIGNMENT_STAFF_INELIGIBLE';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_care_assignment_general_care_qualified()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.invalidated_at_utc IS NULL
               AND NEW.assignment_kind = 'GENERAL'
               AND EXISTS (
                   SELECT 1
                   FROM erp.recipient_contract contract
                   WHERE contract.id = NEW.recipient_contract_id
                     AND contract.invalidated_at_utc IS NULL
                     AND NOT (
                         NEW.assignment_period <@ COALESCE(
                             (
                                 SELECT range_agg(qualification.qualification_period)
                                 FROM erp.staff_service_qualification_period qualification
                                 WHERE qualification.staff_id = NEW.staff_id
                                   AND qualification.employment_id = NEW.employment_id
                                   AND qualification.service_type_id = contract.service_type_id
                                   AND qualification.invalidated_at_utc IS NULL
                             ), '{}'::datemultirange
                         )
                     )
               )
            THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'CARE_ASSIGNMENT_STAFF_INELIGIBLE';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_recipient_contract_assignment_reverse_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM erp.care_assignment assignment
                WHERE assignment.recipient_contract_id = NEW.id
                  AND assignment.invalidated_at_utc IS NULL
                  AND (
                      NEW.invalidated_at_utc IS NOT NULL
                      OR NOT (assignment.assignment_period <@ NEW.contract_period)
                      OR (
                          assignment.assignment_kind = 'GENERAL'
                          AND NOT (
                              assignment.assignment_period <@ COALESCE(
                                  (
                                      SELECT range_agg(
                                          qualification.qualification_period
                                      )
                                      FROM erp.staff_service_qualification_period
                                          qualification
                                      WHERE qualification.staff_id = assignment.staff_id
                                        AND qualification.employment_id =
                                            assignment.employment_id
                                        AND qualification.service_type_id =
                                            NEW.service_type_id
                                        AND qualification.invalidated_at_utc IS NULL
                                  ), '{}'::datemultirange
                              )
                          )
                      )
                  )
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'CARE_ASSIGNMENT_CONTRACT_ORPHAN_FORBIDDEN';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE OR REPLACE FUNCTION erp.fn_staff_employment_child_periods_reverse_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM erp.staff_position_period child
                WHERE child.employment_id = NEW.id AND child.staff_id = NEW.staff_id
                  AND child.invalidated_at_utc IS NULL
                  AND (NEW.invalidated_at_utc IS NOT NULL
                       OR child.start_date < NEW.start_date
                       OR (NEW.end_date IS NOT NULL
                           AND (child.end_date IS NULL OR child.end_date > NEW.end_date)))
            ) OR EXISTS (
                SELECT 1 FROM erp.staff_operational_role_period child
                WHERE child.employment_id = NEW.id AND child.staff_id = NEW.staff_id
                  AND child.invalidated_at_utc IS NULL
                  AND (NEW.invalidated_at_utc IS NOT NULL
                       OR child.start_date < NEW.start_date
                       OR (NEW.end_date IS NOT NULL
                           AND (child.end_date IS NULL OR child.end_date > NEW.end_date)))
            ) OR EXISTS (
                SELECT 1 FROM erp.staff_service_qualification_period child
                WHERE child.employment_id = NEW.id AND child.staff_id = NEW.staff_id
                  AND child.invalidated_at_utc IS NULL
                  AND (NEW.invalidated_at_utc IS NOT NULL
                       OR child.start_date < NEW.start_date
                       OR (NEW.end_date IS NOT NULL
                           AND (child.end_date IS NULL OR child.end_date > NEW.end_date)))
            ) OR EXISTS (
                SELECT 1 FROM erp.care_assignment child
                WHERE child.employment_id = NEW.id AND child.staff_id = NEW.staff_id
                  AND child.invalidated_at_utc IS NULL
                  AND (NEW.invalidated_at_utc IS NOT NULL
                       OR child.start_date < NEW.start_date
                       OR (NEW.end_date IS NOT NULL
                           AND (child.end_date IS NULL OR child.end_date > NEW.end_date)))
            )
            THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'STAFF_PERIOD_OUTSIDE_EMPLOYMENT';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_staff_position_care_assignment_reverse_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM erp.care_assignment assignment
                WHERE assignment.staff_id = OLD.staff_id
                  AND assignment.employment_id = OLD.employment_id
                  AND assignment.assignment_kind = 'GENERAL'
                  AND assignment.invalidated_at_utc IS NULL
                  AND NOT (
                      assignment.assignment_period <@ COALESCE(
                          (
                              SELECT range_agg(position.position_period)
                              FROM erp.staff_position_period position
                              WHERE position.staff_id = assignment.staff_id
                                AND position.employment_id = assignment.employment_id
                                AND position.position_code = 'CARE_WORKER'
                                AND position.invalidated_at_utc IS NULL
                          ), '{}'::datemultirange
                      )
                  )
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'CARE_ASSIGNMENT_POSITION_ORPHAN_FORBIDDEN';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE FUNCTION erp.fn_staff_service_qualification_assignment_reverse_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM erp.care_assignment assignment
                JOIN erp.recipient_contract contract
                  ON contract.id = assignment.recipient_contract_id
                WHERE assignment.staff_id = OLD.staff_id
                  AND assignment.employment_id = OLD.employment_id
                  AND assignment.assignment_kind = 'GENERAL'
                  AND assignment.invalidated_at_utc IS NULL
                  AND contract.invalidated_at_utc IS NULL
                  AND contract.service_type_id = OLD.service_type_id
                  AND NOT (
                      assignment.assignment_period <@ COALESCE(
                          (
                              SELECT range_agg(qualification.qualification_period)
                              FROM erp.staff_service_qualification_period qualification
                              WHERE qualification.staff_id = assignment.staff_id
                                AND qualification.employment_id = assignment.employment_id
                                AND qualification.service_type_id = contract.service_type_id
                                AND qualification.invalidated_at_utc IS NULL
                          ), '{}'::datemultirange
                      )
                  )
            ) THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'CARE_ASSIGNMENT_QUALIFICATION_ORPHAN_FORBIDDEN';
            END IF;
            RETURN NEW;
        END
        $$;

        CREATE CONSTRAINT TRIGGER ct_care_assignment_within_contract
        AFTER INSERT OR UPDATE ON erp.care_assignment
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION erp.fn_care_assignment_within_contract();

        CREATE CONSTRAINT TRIGGER ct_care_assignment_within_employment
        AFTER INSERT OR UPDATE ON erp.care_assignment
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION erp.fn_care_assignment_within_employment();

        CREATE CONSTRAINT TRIGGER ct_care_assignment_within_position
        AFTER INSERT OR UPDATE ON erp.care_assignment
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION erp.fn_care_assignment_within_position();

        CREATE CONSTRAINT TRIGGER ct_care_assignment_general_care_qualified
        AFTER INSERT OR UPDATE ON erp.care_assignment
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION erp.fn_care_assignment_general_care_qualified();

        CREATE CONSTRAINT TRIGGER ct_recipient_contract_assignment_reverse_guard
        AFTER UPDATE ON erp.recipient_contract
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION erp.fn_recipient_contract_assignment_reverse_guard();

        CREATE CONSTRAINT TRIGGER ct_staff_position_care_assignment_reverse_guard
        AFTER UPDATE ON erp.staff_position_period
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION erp.fn_staff_position_care_assignment_reverse_guard();

        CREATE CONSTRAINT TRIGGER ct_staff_service_qualification_assignment_reverse_guard
        AFTER UPDATE ON erp.staff_service_qualification_period
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW EXECUTE FUNCTION erp.fn_staff_service_qualification_assignment_reverse_guard();
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_app') THEN
                GRANT USAGE ON SCHEMA erp TO erp_app;
                GRANT SELECT, INSERT, UPDATE ON TABLE erp.care_assignment TO erp_app;
                REVOKE DELETE, TRUNCATE ON TABLE erp.care_assignment FROM erp_app;
                GRANT USAGE, SELECT ON SEQUENCE erp.care_assignment_id_seq TO erp_app;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_backup') THEN
                GRANT USAGE ON SCHEMA erp TO erp_backup;
                GRANT SELECT ON TABLE erp.care_assignment TO erp_backup;
                REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON TABLE erp.care_assignment
                    FROM erp_backup;
                GRANT SELECT ON SEQUENCE erp.care_assignment_id_seq TO erp_backup;
                REVOKE USAGE ON SEQUENCE erp.care_assignment_id_seq FROM erp_backup;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_app') THEN
                REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE
                    erp.care_assignment FROM erp_app;
                REVOKE USAGE, SELECT ON SEQUENCE erp.care_assignment_id_seq FROM erp_app;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_backup') THEN
                REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE
                    erp.care_assignment FROM erp_backup;
                REVOKE USAGE, SELECT ON SEQUENCE erp.care_assignment_id_seq FROM erp_backup;
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        DROP TRIGGER IF EXISTS ct_care_assignment_within_contract ON erp.care_assignment;
        DROP TRIGGER IF EXISTS ct_care_assignment_within_employment ON erp.care_assignment;
        DROP TRIGGER IF EXISTS ct_care_assignment_within_position ON erp.care_assignment;
        DROP TRIGGER IF EXISTS ct_care_assignment_general_care_qualified ON erp.care_assignment;
        DROP TRIGGER IF EXISTS ct_recipient_contract_assignment_reverse_guard
            ON erp.recipient_contract;
        DROP TRIGGER IF EXISTS ct_staff_position_care_assignment_reverse_guard
            ON erp.staff_position_period;
        DROP TRIGGER IF EXISTS ct_staff_service_qualification_assignment_reverse_guard
            ON erp.staff_service_qualification_period;
        DROP FUNCTION IF EXISTS erp.fn_care_assignment_within_contract();
        DROP FUNCTION IF EXISTS erp.fn_care_assignment_within_employment();
        DROP FUNCTION IF EXISTS erp.fn_care_assignment_within_position();
        DROP FUNCTION IF EXISTS erp.fn_care_assignment_general_care_qualified();
        DROP FUNCTION IF EXISTS erp.fn_recipient_contract_assignment_reverse_guard();
        DROP FUNCTION IF EXISTS erp.fn_staff_position_care_assignment_reverse_guard();
        DROP FUNCTION IF EXISTS erp.fn_staff_service_qualification_assignment_reverse_guard();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION erp.fn_staff_employment_child_periods_reverse_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM erp.staff_position_period child
                WHERE child.employment_id = NEW.id
                  AND child.staff_id = NEW.staff_id
                  AND child.invalidated_at_utc IS NULL
                  AND (
                      NEW.invalidated_at_utc IS NOT NULL
                      OR child.start_date < NEW.start_date
                      OR (
                          NEW.end_date IS NOT NULL
                          AND (child.end_date IS NULL OR child.end_date > NEW.end_date)
                      )
                  )
            ) OR EXISTS (
                SELECT 1
                FROM erp.staff_operational_role_period child
                WHERE child.employment_id = NEW.id
                  AND child.staff_id = NEW.staff_id
                  AND child.invalidated_at_utc IS NULL
                  AND (
                      NEW.invalidated_at_utc IS NOT NULL
                      OR child.start_date < NEW.start_date
                      OR (
                          NEW.end_date IS NOT NULL
                          AND (child.end_date IS NULL OR child.end_date > NEW.end_date)
                      )
                  )
            ) OR EXISTS (
                SELECT 1
                FROM erp.staff_service_qualification_period child
                WHERE child.employment_id = NEW.id
                  AND child.staff_id = NEW.staff_id
                  AND child.invalidated_at_utc IS NULL
                  AND (
                      NEW.invalidated_at_utc IS NOT NULL
                      OR child.start_date < NEW.start_date
                      OR (
                          NEW.end_date IS NOT NULL
                          AND (child.end_date IS NULL OR child.end_date > NEW.end_date)
                      )
                  )
            )
            THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    MESSAGE = 'STAFF_PERIOD_OUTSIDE_EMPLOYMENT';
            END IF;
            RETURN NEW;
        END
        $$;
        """
    )
    op.drop_table(_TABLE, schema="erp")
